[tool.poetry]
name = "thymis-controller"
version = "0.1.0"
description = ""
authors = ["Adrian Block <adrian.block@thymis.io>", "Eli Kogan-Wang <eli.kogan-wang@thymis.io", "Maximilian Schmöcker <maximilian.schmoecker@thymis.io>", "Florian Schönlau <florian.schoenlau@thymis.io"]
license = "AGPLv3"
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = ">=3.10"
fastapi = "^0.103.2"
pydantic = "^2.4.2"
uvicorn = "^0.23.2"
jinja2 = "^3.1.2"
python-dotenv = "^1.0.1"
websockets = "^12.0"
gitpython = "^3.1.41"

[tool.poetry.group.enterprise]
optional = true

[tool.poetry.group.enterprise.dependencies]
thymis-enterprise = { path = "../../thymis-enterprise/py" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
thymis-controller = 'app.api:run'
